org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true

# Required dependencies
minecraft=26.1
fabric_loader=0.18.4
fabric_api=0.144.3+26.1
owo_lib=0.13.0+26.1

# Local dependencies
modmenu=18.0.0-alpha.8
sodium=mc26.1-0.8.7-fabric
lithium=mc1.21.11-0.21.4-fabric
noisium=2.8.3+mc1.21.11
c2me=0.3.7+alpha.0.9+1.21.11
scalablelux=0.1.6+fabric.c25518a
ferritecore=8.2.0-fabric
patchouli=1.21-87-FABRIC
rei=16.0.783
emi=1.1.16+1.21.1+fabric
lambdynamiclights=4.9.1+1.21.11

# Project detail
mod_version=1.1.0+26.1
maven_group=io.github.realguyman
archives_base_name=totally_lit
